/**
 * RuralMed Service Worker
 *
 * Handles static asset caching only.
 * Data synchronization is handled exclusively by PowerSync (local SQLite + WebSocket).
 * DO NOT add any API route caching here.
 */

// Injected by vite-plugin-pwa at build time — precaches static shell assets
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';

// Precache all static assets (HTML, CSS, JS, images) generated by Vite
// The __WB_MANIFEST array is injected at build time by vite-plugin-pwa
precacheAndRoute(self.__WB_MANIFEST);

// Remove old caches from previous service worker versions
cleanupOutdatedCaches();

// ── Navigation fallback ────────────────────────────────────────────────────
// For SPA routing: serve index.html for all non-asset navigations
self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);

  // Skip: non-GET requests
  if (request.method !== 'GET') return;

  // Skip: API calls — PowerSync handles data sync, Workbox must NOT intercept these
  if (url.pathname.startsWith('/api/')) return;

  // Skip: PowerSync WebSocket connections
  if (url.protocol === 'wss:' || url.protocol === 'ws:') return;

  // Skip: Cross-origin requests (fonts, CDN, etc.)
  if (url.origin !== self.location.origin) return;
});

// ── Activate immediately ───────────────────────────────────────────────────
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});
